---
# Logging & Tomcat
server:
  tomcat:
    max-threads: 10

monitoringAgent:
  statsd:
    hostname: "statsd-int.us-west-2.test.expedia.com"
    port: 8125

# Additional Config
test:
  helloMsg: "Hello Int user"
